### ISSUE TITLE
Example using unique_resource as a class member

### ISSUE THREAD

**Issue by gotnone** [PeterSommerlad/scope17#10]
**Is your feature request related to a problem? Please describe.**
I was not able to find an example of how to use unique_resource as a class member.

**Describe the solution you'd like**
I am not even sure that it is currently possible to use unique_resource as a class member, but I would either like to see some clarification on how one might do so, or a clear warning that this template is not useful as a class member.  I appreciate the fact that unique_resource can manage a variety of resource handles, but being able to use this as a class member would be even more useful.

**Describe alternatives you've considered**
I was not able to determine a way to use unique_resource as a class member.  I can wrap my head around how to create a unique_ptr as a class member.  I can often initialize unique_ptr to  nullptr during the member initialization of the ctor, and then reset() the pointer when the resource is actually acquired.

**Additional context**

**Comment by PeterSommerlad** [comment]
Just briefly because I have a phone only to type:

You need to specify unique_resource template arguments when defining the member. If you want the deleter be a lambda, you make that a constexpr static inline member of your class and use decltype on the unique resource template argument.

**Comment by gotnone** [comment]
Thanks Peter,
I am running into an issue on g++ 7.4 on my development computer and g++ 9.2 on godbolt.org with constexpr static inline lambda class members.  When I make a class in a separate header file it gives a warning that the unique_resource member is a type that uses the anonymous namespace.  If I include this class into multiple translation units and then combine them, doesn't this mean that the ODR rule is going to be violated?

> warning: 'TestUR' has a field 'TestUR::handle_' whose type uses the anonymous namespace [-Wsubobject-linkage]

[TestUR class with constexpr static inline lambda members (godbolt.org)](https://godbolt.org/z/xULlKL)
Be sure to turn on compiler output and wrap lines to see the warning.

[Header file and Program code to test TestUR class](https://gist.github.com/gotnone/4f45de527879507e09fc6115aad93f80)

**Comment by PeterSommerlad** [comment]
For a pointer resource, better use unique_ptr anyway....

Second, clang seems to accept without a warning. this might be a bug in gcc's implementation of either lambdas, or inline static members...

But you do not need such a lambda...

Try:

```C++
#ifndef TEST_UR_HPP
#include <iostream>
#include <string>
//#include <scope17>
//#include <https://raw.githubusercontent.com/PeterSommerlad/scope17/master/scope.hpp>

struct __handle {};
typedef struct __handle *handle;
constexpr int HANDLE_NO_ERROR = 0;
constexpr int HANDLE_CREATE_ERROR = 1;

int makeHandle(handle &hp) { // i consider such a factory with side effects bad code, changed at least to take a reference instead of a pointer...
// and it shows, you were needing a trampoline below
  hp = new __handle;
  std::cout << "constructed handle\n";
  return hp ? HANDLE_NO_ERROR : HANDLE_CREATE_ERROR;
}
// if you have a deleter function, just wrap it into a deleter class, there is no need for a lambda.
// a lambda would only be necessary if you want to avoid having such an explicitly named type.
struct delHandle {
void operator()(handle h) const {
  std::cout << "destroying handle\n";
  delete h; // works also when h is nullptr....
}
};

class TestUR {


public:
  using ur_handle =
      std::experimental::unique_resource<handle, delHandle>;
  TestUR() : handle_(make_ur_handle()) {}
  const std::string string() const {
    return std::to_string((size_t)handle_.get());
  }

private:
  constexpr static inline auto make_ur_handle = []() {
    handle h;
    makeHandle(&h);
    return ur_handle(h, delHandle{}); // an implementation might actually default the deleter argument if none is given, but when I started, lambdas where not yet default constructible 
  };
  ur_handle handle_;
};
#define TEST_UR_HPP
#endif /* ifndef TEST_UR_HPP */
```

**Comment by gotnone** [comment]
Peter, thanks for the tips, they got me back on track and satisfied gcc's complaint about anonymous namespaces.

Unfortunately, my actual use case "handle" is coming from a C library.  Yes, it does use a factory function with side effects.  It is probably using malloc under the hood and seems to dynamically allocate some of it's own members (at least that is my understanding from the documentation), so I need to use the library provided destructor function.  I apologize if my example was a bit simplified.

It is true that I currently use unique_pointer with the library provided destructor, but since I don't control the implementation, it is possible that a future revision of this C library may change "handle" from a pointer to "struct __handle" to something else.  I also wanted to get some experience with this template to see if I can use it with Windows handles and other opaque resources which need some wrangling or wrapping to shoehorn into unique_pointer.

Am I being overly defensive in checking for nullpointer in the destructor?  I am not sure that I trust the library implementers to handle the case when a null pointer is passed to their actual destructor for "handle".  Does unique_resource call the destructor function provided in the template in the case where handle has been moved from it to another unique_resource instance and the now empty unique_resource goes out of scope?  If it does not call the template provided destructor, I can probably drop the nullpointer check in my destructor.
