### ISSUE TITLE
make this library a standalone one

### ISSUE THREAD

**Issue by uyha** [PeterSommerlad/scope17#20]
I'm aware that this library was developed as an example implementation for [P0052](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0052r10.pdf), but it seems that after being accepted into LFTS3, there is no push to have it out of the experimental header anymore. There is no deny that this is an awesome piece of library and it's a shame that it's not more popular. 

Currently, there is a few problems with this library, it lives in either the `std::experimental` or `boost` namespace.
- Using this library with the `std::experimental` is UB as far as my understanding of the standard. 
- Using the `boost` namespace is confusing since this is not part of the boost library, and it also doesn't compile (easy to fix).

Another problem is this library doesn't have a release version, which makes it difficult to put on conan-center-index since the maintainers require upstream to have a release version to be put on their index (I am not familiar with the policies of vcpkg).

So I'm suggesting the following:
- [ ] Move this library to the `scope` namespace
- [ ] Fix the compilation error
- [ ] Release either a v0.1 version or v1.0

**Comment by PeterSommerlad** [comment]
I am happy to accept corresponding pull requests.

**Comment by uyha** [comment]
I think I have jumped the gun since I created a [fork](https://github.com/uyha/scope) and made some heavy modifications to the project setup (regarding CI and testing library). So I think I will maintain a seperate fork.
