### ISSUE TITLE
unique_resource with static Deleter

### ISSUE THREAD

**Issue by nolange** [PeterSommerlad/scope17#8]
Hello,

**Abstract**

I am a bit unsure about the ~~scope~~ intended use of this library.
My requirement would be to have some convenient handle, that I can also easily use as members in classes.
The `make_*` functions with type-deduction is nice for use on `scope`, less you if you move the resource into predefined variables.

**Wishes**

I would like some clarification if this class is intended as persistent storage type, like a `unique_resource<int, decltype(::close)>` member variable for descriptors.
There are some drawbacks like having to store the pointer to a static functions in every instance for such kind of "Deleters".

**Motivation Proposal**

I cooked up parts of such a solution a long time ago (never used it anywhere though), ie. some specific subsystem and resource-handlers like one for filedescriptors, and a generic resource class like `unique_resource` (actually it was more concerning different allocation schemes).

You would have some specialized `unique_resource_static` class using a compile time parameter like pointer to a function instead of a `deleter` member. And a `unique_resource` class having a runtime member (like the one in your project).

Moving `unique_resource_static` to `unique_resource` should be easily possibly (within the confines of matching deleter types), moving back would require a check if the deleter is identical to the static instance.

**Additional context**
I taken the priviledge to adopt your class to use a templatized static deleter. I consider this to be a worthwhile addition (no overhead compared to using raw filedescriptors).
This could be made more flexible with another type deduction step (handling ret type and argument passing R*, R&, R for the deleter), so the signature would be `template<typename R, typename D, D tFunc> class unique_resource_static`

```cpp
template<typename R, typename Ret, Ret (*tFunc)(R)>
class unique_resource_static
{
    static_assert((std::is_move_constructible_v<R> && std::is_nothrow_move_constructible_v<R>) ||
                  std::is_copy_constructible_v<R>,
                  "resource must be nothrow_move_constructible or copy_constructible");

    static const unique_resource_static &this_; // never ODR used! Just for getting no_except() expr

    detail::_box<R> resource;
    bool execute_on_destruction { true };

    static constexpr auto is_nothrow_delete_v=std::bool_constant<noexcept(tFunc(std::declval<R *>()))>::value;

    template<typename RR,
        typename = std::enable_if_t<std::is_constructible_v<detail::_box<R>, RR, detail::_empty_scope_exit>>>
    unique_resource_static(RR &&r, bool should_run)
    noexcept(noexcept(detail::_box<R>(std::forward<RR>(r), detail::_empty_scope_exit {})))
      : resource{std::forward<RR>(r), scope_exit([&] {if (should_run) tFunc(r);})}
      , execute_on_destruction { should_run }
    {}
    friend struct detail::hidden::factory_holder;  // a level of indirection is the trick...
public:
    template<typename RR,
        typename = std::enable_if_t<std::is_constructible<detail::_box<R>, RR, detail::_empty_scope_exit>::value >
    >
    unique_resource_static(RR &&r)
    noexcept(noexcept(detail::_box<R>(std::forward<RR>(r), detail::_empty_scope_exit {})))
      : resource(std::forward<RR>(r), scope_exit([&] {tFunc(r);}))
    {}
    unique_resource_static(    unique_resource_static&& that)
    noexcept(noexcept(detail::_box<R>(that.resource.move(), detail::_empty_scope_exit {})))
        : resource(that.resource.move(), detail::_empty_scope_exit { })
         , execute_on_destruction(std::exchange(that.execute_on_destruction, false))
        { }

    unique_resource_static &operator=(unique_resource_static &&that) noexcept(is_nothrow_delete_v &&
            std::is_nothrow_move_assignable_v<R>)
    {
        static_assert(std::is_nothrow_move_assignable<R>::value ||
                std::is_copy_assignable<R>::value,
                "The resource must be nothrow-move assignable, or copy assignable");
        if (&that != this) {
            reset();
            resource = std::move(that.resource);
            execute_on_destruction = std::exchange(that.execute_on_destruction, false);
        }
        return *this;
    }
    ~unique_resource_static()
    {
        reset();
    }

    void reset() noexcept
    {
        if(execute_on_destruction)
        {
            execute_on_destruction = false;
            get_deleter()(get());
        }
    }
    template<typename RR>
    auto reset(RR &&r)
        noexcept(noexcept(resource.reset(std::forward<RR>(r))))
    -> decltype(resource.reset(std::forward<RR>(r)), void())
    {
        auto &&guard = scope_fail([&, this]{ get_deleter()(r); }); // -Wunused-variable on clang
        reset();
        resource.reset(std::forward<RR>(r));
        execute_on_destruction = true;
    }
    void release() noexcept
    {
        execute_on_destruction = false;
    }
    decltype(auto) get() const noexcept
    {
        return resource.get();
    }
    decltype(auto) get_deleter() const noexcept
    {
        return tFunc;
    }
    // THIS IS NOT A POINTER TYPE, the following operations are only available if R is a native pointer
    template<typename RR=R>
    auto operator->() const noexcept
    -> std::enable_if_t<std::is_pointer_v<RR>,decltype(get())>
    {
        return get();
    }
    template<typename RR=R>
    auto operator*() const noexcept
        -> std::enable_if_t<std::is_pointer_v<RR> && ! std::is_void_v<std::remove_pointer_t<RR>>,
        std::add_lvalue_reference_t<std::remove_pointer_t<R>>>
    {
        return *get();
    }

    // implicitly deleted:
//  unique_resource_static& operator=(const unique_resource &) = delete;
//  unique_resource_static(const unique_resource &) = delete;
};
```

**Comment by PeterSommerlad** [comment]
Hi,
sorry for the late reply, but your issue reached my while on vacation. Thank you for your proposal.

I plan not to spend too much time on the current design of unique_resource, because I got some fundamental design flaw feedback and the idea to split it into a non-movable "scoped_resource" and a movable "unique_resource" in a future standard library proposal.

BTW, you are not allowed to take the address of any function provided by the C++ standard library (such as the ::close or ::fcloase transitively provided via the included C standard library), therefore your pointer version might not work as expected portably, even so it might work in all relevant implementations.

A better implementation should also provide empty-base-class optimization for the deleter, if it is a class type by inheriting from it, such as unique_ptr is doing.

Regards
Peter.

**Comment by nolange** [comment]
> Hi,
> sorry for the late reply, but your issue reached my while on vacation. Thank you for your proposal.
> 
> I plan not to spend too much time on the current design of unique_resource, because I got some fundamental design flaw feedback and the idea to split it into a non-movable "scoped_resource" and a movable "unique_resource" in a future standard library proposal.

I just found another proposal 'unique_val'. Still unsure where to go, pragmatically I need something that works first, but of course I would like to switch to a std class ASAP.

> BTW, you are not allowed to take the address of any function provided by the C++ standard library (such as the ::close or ::fcloase transitively provided via the included C standard library), therefore your pointer version might not work as expected portably, even so it might work in all relevant implementations.

I am aware that the C Standard takes some liberties to implement some functions as macros. But I am not aware of a similar issue with C++ (needs to work with namespaces after all).
But thats not a blocking issue, you can always use function stubs or lambdas.

> 
> A better implementation should also provide empty-base-class optimization for the deleter, if it is a class type by inheriting from it, such as unique_ptr is doing.
> 
> Regards
> Peter.
